language: objective-c
xcode_project: EmarsysPredictSDK.xcodeproj
xcode_scheme: EmarsysPredictSDK
osx_image: xcode7.2
sudo: false
notifications:
  email:
    - dev@scarabresearch.com
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - APP_NAME="EmarsysPredictSDK"
  - PROFILE_NAME="EmarsysPredictSDK"
script:
  - set -o pipefail
  - xctool test -project EmarsysPredictSDK.xcodeproj -scheme EmarsysPredictSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -project EmarsysPredictSDK.xcodeproj -scheme EmarsysPredictSDK -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
  - xctool -project EmarsysPredictSDK.xcodeproj -scheme EmarsysPredictSDK -sdk iphonesimulator -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_script:
  - ./scripts/deploy.sh
after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
