language: objective-c
xcode_project: EmarsysPredictSDK.xcodeproj
xcode_scheme: EmarsysPredictSDK
osx_image: xcode7.2
sudo: false
notifications:
  email:
    - dev@scarabresearch.com
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - APP_NAME="EmarsysPredictSDK"
  - PROFILE_NAME="EmarsysPredictSDK"
script:
  - set -o pipefail
after_script:
  - ./scripts/deploy.sh
after_failure:
  - cat -n ~/Library/Logs/scan/*
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
